name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: 3.3
            gemfile: gemfiles/activerecord72.gemfile
            postgres: 16
          - ruby: 3.3
            gemfile: Gemfile
            postgres: 14
          - ruby: 3.2
            gemfile: gemfiles/activerecord70.gemfile
            postgres: 12
          - ruby: 3.1
            gemfile: gemfiles/activerecord61.gemfile
            postgres: 10
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - uses: ankane/setup-postgres@v1
        with:
          postgres-version: ${{ matrix.postgres }}
          database: pghero_test
          config: |
            shared_preload_libraries = 'pg_stat_statements'
      - run: bundle exec rake test
